name: GitHub Actions Demo
on: 
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull:
    branches: [ main ]
  schedule:
    -cron: '15 6 * * 0'
  workflow_dispatch:
    jobs:
      Build:
        runs-on: ubuntu-latest
        steps:
          - run: |
              echo "Event triggered by ${{ github.event_name }}."
              echo "The branch name is ${{ github.ref }}." 
              
          - uses: actions/checkout@v3.3.0
  
          -name: List files
          run: |
            echo "The repo ${{ github.repository }} contains:"
            tree
